create table gdelt (
    GLOBALEVENTID integer, 
    SQLDATE integer, 
    MonthYear integer, 
    Year integer, 
    FractionDate double precision, 
    Actor1Code varchar, 
    Actor1Name varchar, 
    Actor1CountryCode varchar, 
    Actor1KnownGroupCode varchar, 
    Actor1EthnicCode varchar, 
    Actor1Religion1Code varchar, 
    Actor1Religion2Code varchar, 
    Actor1Type1Code varchar, 
    Actor1Type2Code varchar, 
    Actor1Type3Code varchar, 
    Actor2Code varchar, 
    Actor2Name varchar, 
    Actor2CountryCode varchar, 
    Actor2KnownGroupCode varchar, 
    Actor2EthnicCode varchar, 
    Actor2Religion1Code varchar, 
    Actor2Religion2Code varchar, 
    Actor2Type1Code varchar, 
    Actor2Type2Code varchar, 
    Actor2Type3Code varchar, 
    IsRootEvent varchar, 
    EventCode varchar, 
    EventBaseCode varchar, 
    EventRootCode varchar, 
    QuadClass integer, 
    GoldsteinScale double precision, 
    NumMentions integer, 
    NumSources integer, 
    NumArticles integer, 
    AvgTone double precision, 
    Actor1Geo_Type integer, 
    Actor1Geo_FullName varchar, 
    Actor1Geo_CountryCode varchar, 
    Actor1Geo_ADM1Code varchar, 
    Actor1Geo_Lat double precision, 
    Actor1Geo_Long double precision, 
    Actor1Geo_FeatureID integer, 
    Actor2Geo_Type integer, 
    Actor2Geo_FullName varchar, 
    Actor2Geo_CountryCode varchar, 
    Actor2Geo_ADM1Code varchar, 
    Actor2Geo_Lat varchar, 
    Actor2Geo_Long double precision, 
    Actor2Geo_FeatureID double precision, 
    ActionGeo_Type integer, 
    ActionGeo_FullName varchar, 
    ActionGeo_CountryCode varchar, 
    ActionGeo_ADM1Code varchar, 
    ActionGeo_Lat varchar, 
    ActionGeo_Long double precision, 
    ActionGeo_FeatureID double precision, 
    DATEADDED integer, 
    SOURCEURL varchar
);

create table gdelt_reduced(
    GLOBALEVENTID integer, 
    SQLDATE integer, 
    MonthYear integer, 
    Year integer, 
    FractionDate double precision, 
    Actor1Code varchar, 
    Actor1Name varchar, 
    Actor1CountryCode varchar, 

    Actor2Code varchar, 
    Actor2Name varchar, 
    Actor2CountryCode varchar, 

    EventCode varchar, 

    GoldsteinScale double precision, 

    AvgTone double precision, 

    Actor1Geo_FullName varchar, 
    Actor1Geo_CountryCode varchar, 

    Actor1Geo_Lat double precision, 
    Actor1Geo_Long double precision, 

    Actor2Geo_FullName varchar, 
    Actor2Geo_CountryCode varchar, 

    Actor2Geo_Lat varchar, 
    Actor2Geo_Long double precision
);
